# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types: 
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  dev:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: 
      name: dev
    # Steps represent a sequence of tasks that will be executed as part of the job
   
    steps:
      - name: Deploy
        run: echo 'Deploying...'
  qa:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: 
      name: qa
    # Steps represent a sequence of tasks that will be executed as part of the job
   
    steps:
      - name: Deploy
        run: echo 'Deploying...'
