# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  release:
    types: [published]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
          
  staging:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: 
      name: staging
      url: https://test-url.com
    # Steps represent a sequence of tasks that will be executed as part of the job
   
    steps:
      - name: Deploy
        run: echo 'Deploying...'

  live:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: 
      name: live
      url: https://test-url.com
    # Steps represent a sequence of tasks that will be executed as part of the job
   
    steps:
      - name: Deploy
        run: echo 'Deploying...'
        

